
title: Little Bit
email: agusgambina@gmail.com
description: A pun of information
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://littlebit.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: agusgambina
github_username:  agusgambina

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

google_analytics: UA-121310022-1

disqus:
  shortname: littlebit-me

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
